console.log('🚀 API UGEL Talara - Inicio Rápido');
console.log('');
console.log('📝 Especies de ejecución:');
console.log('');
console.log('1️⃣  LOCAL (solo tu PC)');
console.log('   npm run dev');
console.log('   → http://localhost:9000');
console.log('');
console.log('2️⃣  LOCAL + URL PÚBLICA (ngrok)');
console.log('   npm run public');
console.log('   → http://localhost:9000');
console.log('   → https://xxxx.ngrok.io (URL pública)');
console.log('   → Útil para compartir y probar');
console.log('');
console.log('3️⃣  NUBE (Permanente - Render.com)');
console.log('   1. Ve a https://render.com');
console.log('   2. Conecta tu GitHub');
console.log('   3. Crea Web Service');
console.log('   4. ¡Listo! API pública permanente');
console.log('');
console.log('📚 Documentación:');
console.log('   - INICIO_RAPIDO.md (Este archivo)');
console.log('   - COMO_PUBLICAR_TU_API.md (Nube)');
console.log('   - GUIA_DESPLIEGUE.md (Completa)');
console.log('');
console.log('🎯 Recomendación:');
console.log('   Para prueba rápida: npm run public');
console.log('   Para producción: Despliega en Render.com');
console.log('');
console.log('¿Listo para empezar?');
